### ISSUE TITLE
DAC8564

### ISSUE THREAD

**Issue by goerserr** [eh2k/squares-and-circles#13]
Hi, I have 2xO&C built with DAC8564. The only difference in original firmware is that you must set RST pin to LOW instead of HIGH. I can't find similar DAC setup in s&c. Where should I look?

**Comment by eh2k** [comment]
Hi, that's good to know about the alternative dac.

It is not directly possible to change hardware settings in the code - but I think it should not be too complicated to add a setting or similar in the next release.

**Comment by eh2k** [comment]
Hi @goerserr,
It is now possible to execute certain setup commands. Could you please confirm that it works with the DAC8564.
Please flash the latest firmware with [![WebFlasher](https://img.shields.io/badge/Firmware-WebFlasher-blue)](https://eh2k.github.io/□●/flash/?ver=RC_0.0m) and execute the setup command.

![image](https://user-images.githubusercontent.com/11786292/188304814-2229cbe2-8202-4347-b3c3-25a83dbded45.png)
