### ISSUE TITLE
o_c reboots when trying to open I/O menu on the MIDI Clock engine

### ISSUE THREAD

**Issue by spiilmusic** [eh2k/squares-and-circles#18]
I don't know if this were in the previous versions, but I reproduces this on 0.0m

**Comment by eh2k** [comment]
Hello @spiilmusic,

thanks for the hint:

The issue should be fixed in the latest version: [![WebFlasher](https://img.shields.io/badge/RC_0.0N-WebFlasher-blue)](https://eh2k.github.io/□●/flash/?ver=RC_0.0N)
