### ISSUE TITLE
Screenatifacts when returning from screensaver.

### ISSUE THREAD

**Issue by eh2k** [eh2k/squares-and-circles#20]
Have a little bit problems when returning from screensaver.
![DSC08703](https://user-images.githubusercontent.com/110163288/190218294-dc1a94b6-7299-430d-b987-5cfe76e419ba.JPG)

_Originally posted by @tsanderakis in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1247062816_

**Comment by eh2k** [comment]
Hello @tsanderakis, thanks for reporting the issue.

The screensaver can be activated by pressing the "left button" for 2 seconds, without waiting 5 minutes.

Does this happen every time, or only once by chance? Could you please make a short test series and tell me how often it happens. For example, in 5 attempts on your device?

**Comment by tsanderakis** [comment]
Don`t know which Firmware I have, but for me it is not possible to switch
on the screensaver by left switch and also tried to press the encoder
switches. In the moment I can`t find a system behind. 10 minutes ago the
komplete sound was off. After starting the rack new everything was fine
again. We`ll keep in touch and I`ll let you know if I can find something.
My PSU should be strong enough.

Am Mi., 14. Sept. 2022 um 19:45 Uhr schrieb eh2k ***@***.***>:

**Comment by eh2k** [comment]
@tsanderakis, 

You can see the version number in the startup screen.
If you do not have the current version, please upgrade to the latest [![WebFlasher](https://img.shields.io/badge/RC_0.0N-WebFlasher-blue)](https://eh2k.github.io/□●/flash/?ver=RC_0.0N) version.

**Comment by eh2k** [comment]
> ![DSC08709](https://user-images.githubusercontent.com/110163288/190585305-ddfadd16-448e-494e-a44e-374cb927b6de.JPG)
Wednesday 3 hours and yesterday 10 hours torturing the firmware 0.0N with Mutable Grids. On wednesday two times I had hanging pixels in same place. Screen refresh? Yesterday in these 10 hours everything was perfect. No frozen engine, no pixels und for now it`s looking good. Have only tested the drum department.

> _Originally posted by @tsanderakis in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1249040519_

Many thanks for the report:

10 hours without failure is not bad. However, the fact that it occurs despite this is not good. I would perhaps observe this for a while - maybe you can somehow simply reproduce it.

**Comment by tsanderakis** [comment]
Ok, will do another testrun. So what was confusing is 2x in 3 hours and
next day working perfect 10 hours without any problem??

Am Fr., 16. Sept. 2022 um 12:09 Uhr schrieb eh2k ***@***.***>:

**Comment by tsanderakis** [comment]
What I can also do, but maybe in a few days, is to change the module. I`m
in this lucky situation that I have 3 of these O&Cs.

Am Fr., 16. Sept. 2022 um 12:50 Uhr schrieb Siegfried Zander <
***@***.***>:

**Comment by eh2k** [comment]
> 9 hours test with 60 bpm. Running perfect without any problems. I will give it a second try with 200 bpm this afternoon.

_Originally posted by @tsanderakis in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1250020708_

Hello @tsanderakis,

thanks for testing.

I don't think it matters how many bpm it runs at.
However, it would certainly be interesting to know if the problem only occurs on a specific OC or if you also experience it on several devices.

grtz
eh2k

**Comment by eh2k** [comment]
>![DSC08712](https://user-images.githubusercontent.com/110163288/190858323-0e7814eb-e0b4-4e3c-8fc5-8b7fc8214fd9.JPG)
New O&C Hardware. After a little bit more then 1 hour and 170 bpm same problem.

>_Originally posted by @tsanderakis in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1250068074_

Hello @tsanderakis,

thanks for reporting. I read that the problem occurs on two different 14HP O_Cs.
I have made a few adjustments in the 0.0N3 Firmaware [![WebFlasher](https://img.shields.io/badge/RC_0.0N3-WebFlasher-blue)](https://eh2k.github.io/□●/flash/?ver=RC_0.0N3). Could you please flash it and let me know if it you have still any issues.
Thanks in advance

**Comment by eh2k** [comment]
>With the new version my Teensy stays dark. No reaction. Panic. First I was thinking I killed it, but when going to the older firmware everything was working. Giving a second try but looks the same like before. Screen stays black and no reaction. Do I have to do something before flashing with these 3 pushbuttons at the bottom of the flashing page?
>_Originally posted by @tsanderakis in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1250103583_

Hello @tsanderakis,

hmm, thanks - give me another try:

I have reduced the SPI frequency in the RC_0.0N3, somehow there seem to be problems with the initialization. Could you please test this version again [![WebFlasher](https://img.shields.io/badge/RC_0.0N4-WebFlasher-blue)](https://eh2k.github.io/□●/flash/?ver=RC_0.0N4). 

To avoid misunderstandings, could you please name the exact firmware version you are using? I am otherwise unsure of the exact version is used.

Thanks again

**Comment by eh2k** [comment]
Hello @tsanderakis,

a pity it still occurs. Could you please test it with [![WebFlasher](https://img.shields.io/badge/RC_0.0N5-WebFlasher-blue)](https://eh2k.github.io/□●/flash/?ver=RC_0.0N5). I hope that it will work without issues now.
Can you tell me if the display works well when you scroll through the menus etc.?

Many thanks for troubleshooting

>![DSC08713](https://user-images.githubusercontent.com/110163288/190873467-36f61dcb-0bb8-4b2d-acc9-36328763d1d0.JPG)
0.0N4 with 170 bpm
After pressing left encoder it is looking like this

>![DSC08715](https://user-images.githubusercontent.com/110163288/190873537-4979da9c-f783-4020-8333-c5c1069541dc.JPG)

>_Originally posted by @tsanderakis in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1250128729_

**Comment by eh2k** [comment]
Hello @tsanderakis 

you wrote that you have several O_Cs. Did you use the same Teensy Board? What actually happens after the display has this artifacts, and you open the machine menu, is everything then good after that?

Please try to reply in this issue, somehow you always reply in the general feedback thread. Thank you.

> 0.0N5 3 hours with 170 bpm
![DSC08716](https://user-images.githubusercontent.com/110163288/190894374-e9a7a94f-d87f-490b-bacc-eb694a3cf05c.JPG)
![DSC08717](https://user-images.githubusercontent.com/110163288/190894387-d05cf35a-641c-4293-9e11-63ca0525288f.JPG)

_Originally posted by @tsanderakis in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1250225643_

**Comment by tsanderakis** [comment]
The teensy board 4.0 is the same. I changed the O&C module. No. 1 and No 2
testing with ~same result. I bought 2 teensys 4.0 a few weeks ago and if
you give me a little bit of time I try to find the second one. I put it
away in a save place but can`t remember where and in which box. Hardware
problem with teensy?

Am So., 18. Sept. 2022 um 13:16 Uhr schrieb eh2k ***@***.***>:

**Comment by eh2k** [comment]
@tsanderakis 

I'm not sure at the moment whether it's just the display that's having a problem or whether the module is generally crashing or hanging. Can you tell me whether sound comes up or whether you can navigate in the menu afterwards and whether the display corrects itself?

if the module hangs, can you tell me the engines you are using?

**Comment by tsanderakis** [comment]
Fresh Teensy 4.0 out of the bag  Software 0.0N 200 bpm. After 1/2 hour
completely frozen and no chance to wake it up by pushing encoder.
[image: DSC08718.JPG]
Changed the module and after 10 min same problem. Audio out frozen but it
was possible to go back to the menue, but does not show up correctly.
This time I also used the right encoder and now I can see a "moving menue"
from left to right. Looks like the menue is not scrolling smoothly but a
little bit more jumping. And I can start and stop the scrolling by pressing
right encoder.
What do you mean with engines?

Later this afternoon I will take a different PSU and do another test.




Am So., 18. Sept. 2022 um 17:49 Uhr schrieb eh2k ***@***.***>:

**Comment by eh2k** [comment]
@tsanderakis,

> Fresh Teensy 4.0 out of the bag  Software 0.0N 200 bpm. After 1/2 hour
completely frozen and no chance to wake it up by pushing encoder.

ok, then we have a completely different problem here, when it freezes and nothing else works (no menu, no sound).

When this happens again, could you please try pressing the [right encoder] & [right button] at the same time - and tell me if the reset works.

If the reset doesn't work, then the unit is really hanging. It is best to use firmware [![WebFlasher](https://img.shields.io/badge/RC_0.0N4-WebFlasher-blue)](https://eh2k.github.io/□●/flash/?ver=RC_0.0N4).

With the engines I mean e.g. "Drums/FM-Drum". Unfortunately, I don't see which other engines are loaded.

Thank you.
