### ISSUE TITLE
Channel one gate input not working (hardware works with standard OC firmware)

### ISSUE THREAD

**Issue by BAREBONESLDN** [eh2k/squares-and-circles#21]
I've tried several teensy 4's and reflashed the firmware several times (with the two latest versions) but for some reason channel one is not responding to the gate signal. 
I can get audio out of channel one by using the speech synthesis mode.
The gate input tests fine in the testing menu and works correctly with a teensy 3.2 and standard OC firmware.
Any ideas what could be going wrong?

Thanks Phil

**Comment by themoonscientistandco** [comment]
hallo , barebonesldn ,your not alone ,I have the same problem , first i thought it was my fault (clumsy smd soldering)
but on the test page everything seems ok
now that you have the exact same problem on trig input 1 i'm starting to think it's not a hardware problem
grtz
the moonscientist

**Comment by eh2k** [comment]
@BAREBONESLDN @themoonscientistandco 

Please check the Midi-Settings by pressing both (L+R) Buttons.
[![](https://github.com/eh2k/squares-and-circles/raw/main/doc/config_midi.bmp)]

Propable the Midi-Input is "T1" and the port is initalized as "Serial Input".
If it is "USB" so try to change it to "T1" and back to "USB".
After that it should work. Save the Preset with both (L+R) encoder pressed.

It has happened to me before, but I haven't figured out how to reproduce the condition.

**Comment by themoonscientistandco** [comment]
Hallo eh2k . indeed, that was the problem
thx
grtz
the moonscientist

**Comment by BAREBONESLDN** [comment]
Thank you!

Sent from Yahoo Mail on Android 
 
  On Fri, 16 Sept 2022 at 15:41, ***@***.***> wrote:   


@BAREBONESLDN @themoonscientistandco

Please check the Midi-Settings by pressing both (L+R) Buttons.
[]

Propable the Midi-Input is "T1" and the port is initalized as "Serial Input".
If it is "USB" so try to change it to "T1" and back to "USB".
After that it should work. Save the Preset with both (L+R) encoder pressed.

It has happened to me before, but I haven't figured out how to reproduce the condition.

**Comment by BAREBONESLDN** [comment]
Unfortunately this fix did not work for me.
I also tried installing the hew firmware update but no difference.

**Comment by eh2k** [comment]
@BAREBONESLDN,

Please press [left button] while startup, and goto the IO-Test page - there you can test whether the input generally works.
![image](https://user-images.githubusercontent.com/11786292/191046289-5c8cf820-05bf-4fa6-bb54-8113d08dcd06.png)

**Comment by BAREBONESLDN** [comment]
I figured it out it was the trigger input setting on the channel, it was set to -
Hold down right button to enter the sub menu for inputs and channel gain.
