### ISSUE TITLE
CV > Envelope : trig not trig

### ISSUE THREAD

**Issue by PooLP** [eh2k/squares-and-circles#3]
Hi,
Apparently, the new version have a bug, the enveloppe not work.
i'm put my GATE output from CV/Gate interface to TR1 or other TR input of O&C, but the enveloppe is not triggered.

I do not have the problem with DRUMS or M-OSC part, all TR input work, and I/O test all trig work.

Another question, Is it planned to integrate a part of native O&C and Hemisphere modules (sequencer, Qantizer ...) ?

Thanks for great work ;)

ps : The problem appear with old version aslo.

**Comment by eh2k** [comment]
Hi - @PooLP, 
thanks for reporting the bug. It does not work for me either - will try to fix it at the next opportunity. 

I think I will not try to port the hemisphere apps directly. But it might be possible - if I find the time/motivation - that a sequencer in combination with randomness will follow in the future. A quantizer would certainly not be very complex - as far as I know hemisphere uses the braids code for that.

**Comment by eh2k** [comment]
the bug is fixed in a24c2ce3cb2c9c947c12f62303724ffb03d4f27c
Check the latest firmware (https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1107901164)

**Comment by PooLP** [comment]
Sorry for delay, it's works 👍
