### ISSUE TITLE
MIDI via T1 

### ISSUE THREAD

**Issue by eh2k** [eh2k/squares-and-circles#31]
> I've tried MIDI input on T1 and so far its not working for me. ...

_Originally posted by @rheslip in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1399544859_
            
@rheslip

thanks for your feedback.

Do you have more info on how you connected it exactly?

Personally, I actually use midi only via the TR1 jack (midi via usb I have used something via the PC, but have no long-term experience).

For this I used the circuit from the readme. But I think it would be easier to implement, as long as the transister Q1 switches.

<img src="https://github.com/eh2k/squares-and-circles/raw/main/doc/midi2ts.png" />
-

**Comment by rheslip** [comment]
Thanks for the reply.

I'm using an Arturia TS to MIDI adapter which has the + side of MIDI on the tip. I just checked it on the bench and its able to turn on the transistor in the O-C circuit below. The T1 input on O-C is definitely working. So I assume my problem is the software setup.

On the MIDI setup page I have T1 as MIDI in and I've set each of the MIDI-CH#s to 1. I have verified that MIDI is on channel 1. I've tried various settings for trigger in using the resonator engine and I get nothing. If I put an signal on T2 LFO and assign trig to T2 it works. I see nothing in the MIDI monitor engine either.

Am I missing something in the setup?

Thanks, Rich
________________________________
From: eh2k ***@***.***>
Sent: January 28, 2023 7:39 AM
To: eh2k/squares-and-circles ***@***.***>
Cc: rheslip ***@***.***>; Mention ***@***.***>
Subject: [eh2k/squares-and-circles] MIDI via T1 (Issue #31)


I've tried MIDI input on T1 and so far its not working for me. ...

Originally posted by @rheslip<https://github.com/rheslip> in #1 (comment)<https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-1399544859>

@rheslip<https://github.com/rheslip>

thanks for your feedback.

Do you have more info on how you connected it exactly?

Personally, I actually use midi only via the TR1 jack (midi via usb I have used something via the PC, but have no long-term experience).

For this I used the circuit from the readme. But I think it would be easier to implement, as long as the transister Q1 switches.

[https://github.com/eh2k/squares-and-circles/raw/main/doc/midi2ts.png]<https://github.com/eh2k/squares-and-circles/raw/main/doc/midi2ts.png>

-

**Comment by eh2k** [comment]
Sounds like the same issue #31 .

I just tried this on my device - and it works. You have actually done everything right so far:
 * `Engine #1`is assigned to midi channel 1.
 * The midi monitor is running on `#1`.

The only thing you could try is to change the midi input from T1 to USB and back again (there were reports that it somehow doesn't always re-initialize after rebooting).

Otherwise, I suspect that somehow the connection does not fit electrically. Can you tell me exactly which adapter you are using.

**Comment by eh2k** [comment]
I think that a type-c TS adapter unfortunately cannot work. See also discussion https://github.com/eh2k/squares-and-circles/discussions/33

**Comment by rheslip** [comment]
The Arturia adapter (from my Beatstep) is actually a TR. I set the whole thing up on my bench and as you can see there are negative going pulses on the output of Q1 (TR1) on the O-C mini. Tried switching back and forth from T1 to USB input, no joy. USB MIDI does work. If this works for you it should be working on my setup but it doesn't.

![IMG_2441](https://user-images.githubusercontent.com/6502992/215507235-47be55c7-3a2a-423b-acdf-71c01a47f5c2.JPG)
![IMG_2439](https://user-images.githubusercontent.com/6502992/215507271-21977ca7-1c3a-4314-b24d-37e4e6a18440.JPG)
![IMG_2440](https://user-images.githubusercontent.com/6502992/215507291-9e51b86f-769c-4af5-89db-ad1db9a83a3f.JPG)

**Comment by eh2k** [comment]
I looked at the connections of the TR adapter yesterday, and as I understand it, it can't work.

https://minimidi.world/?fbclid=IwAR31TqOyRkvdwaLYCxoU2a89hcy2PF3hltCtRKD7IzD5HbZqzn3m9NmiZzc#types

Please correct me if I am wrong:

![image](https://minimidi.world/MIDI-Input.61adbed5.svg)

The TIP is connected with PIN 4 - and is permanently 5V.
The SLEVE is connected to PIN 5 - that is basically a pull-down, that is connected to the TX GPIO (e.g. https://github.com/eh2k/mutable-instruments-diy-archive/blob/main/docs/static/schematics/Shruthi-Digital-v08.pdf) 

Since the transistor Q1, when it switches, pulls the Teensy pin 0 (TR1) to ground - the serial signal must be read inverted. Could you test if the level at the collector or Teensy PIN 0 changes also between 0 and 3.3V - as I see you are measuring the base of the transistor?

**Comment by rheslip** [comment]
You are correct - a TR adapter will not work regardless of how its wired up because the O-C input inverts the MIDI signal. 

Thanks!
