### ISSUE TITLE
Tall Dog SE

### ISSUE THREAD

**Issue by vnunez89** [eh2k/squares-and-circles#41]
IS it possible to get this to run on the TallDog SE it doesnt use a Teensy But i can still load the same files the teensy uses but I have to use a loader installed on my PC. Thanks in advance

**Comment by eh2k** [comment]
Hi @vnunez89,
I assume TallDog is using Cortex-M4 ( is equivalent to Teensy3.2). This firmware requires Cortex-M7 (Teensy 4.x).

**Comment by vnunez89** [comment]
Okay. Thank you for the clarification. I appreciate it.
