### ISSUE TITLE
modules to sell ?

### ISSUE THREAD

**Issue by pppier** [eh2k/squares-and-circles#56]
hello 
I finally could flash it using windows
I build for friends (usually the more you play the less you solder... ), as hobbist, I do 1, 2 modules at time. 
am I allowed to do it using your firmware? you'd like to have a fee each module i eventually sell ? I'd like to do it in respect of your work, please let me know
bests
pierpaolo cimino

**Comment by eh2k** [comment]
Hello Pierpaole,

I have seen your facebook page, and I like the list of modules you offer. 
I am wondering how many modules are involved and if I could list you here as a "trusted" builder.

I haven't given it much thought yet, but some sponsoring or a collaboration would certainly be great.

Please send me an email to continue this conversation.. (eh2k◯gmx.de)

Eduard
