### ISSUE TITLE
707/909 have problems to flash in the latest

### ISSUE THREAD

**Issue by koswir** [eh2k/squares-and-circles#68]
Hey,
After a few times they have flashed, but before that I had some errors:
![screen1](https://github.com/eh2k/squares-and-circles/assets/151975047/409d8f0e-04a1-4a2d-b364-3e3a92a9bdb5)
![screen2](https://github.com/eh2k/squares-and-circles/assets/151975047/4369f9bc-2432-4b3d-b5d8-ad3c682b4605)
![screen3](https://github.com/eh2k/squares-and-circles/assets/151975047/c7d972e4-71f3-4d31-acc9-9739bd3cd33e)
Once I even got that black screen and o_c stoped to load. 
I had to flash s&c again!

**Comment by eh2k** [comment]
Thanks for reporting - if this happens often or in general, reducing the transmit_frame or increasing the transmit_delay will probably help.

To do this, simply adjust the following parameters in the URL of webflasher:

default:
- `https://eh2k.github.io/□●/flash/...../?&transmit_delay=1&transmit_frame=64`

slower but safer:
- `https://eh2k.github.io/□●/flash/...../?&transmit_delay=1&transmit_frame=16`

It may also be that the problem occurs depending on the engines loaded. It's best to set all engines to GND when flashing (this will happen automatically in the next update)

**Comment by koswir** [comment]
Thank you. I am going to test it! 💯
