### ISSUE TITLE
Calibration troubles 

### ISSUE THREAD

**Issue by BAREBONESLDN** [eh2k/squares-and-circles#8]
Hi,

When I hold down the left button on power up I get the test menu but I can't seem to access the calibration menu?
Any help appreciated.
Thanks!

**Comment by spiilmusic** [comment]
Hi @BAREBONESLDN 
It seems that you need to update to the new firmware i.e. https://github.com/eh2k/squares-and-circles/releases/download/0.0.0/firmware-a24c2.zip . The calibration feature is relatively new

**Comment by BAREBONESLDN** [comment]
Unfortunately there is no hex file for the new version and I don't know how to compile it.  :(
    On Monday, 16 May 2022, 17:19:33 BST, Kirill Kolchin ***@***.***> wrote:  
 
 


Hi @BAREBONESLDN
It seems that you need to update to the new firmware i.e. https://github.com/eh2k/squares-and-circles/releases/download/0.0.0/firmware-a24c2.zip . The calibration feature is relatively new

**Comment by spiilmusic** [comment]
@BAREBONESLDN what version of s_c are you using?
The [archive above](https://github.com/eh2k/squares-and-circles/releases/download/0.0.0/firmware-a24c2.zip) already has the hex file you need.

**Comment by BAREBONESLDN** [comment]
Thanks I figured out how to compile it, it wasn't too hard. :)
    On Wednesday, 18 May 2022, 11:31:10 BST, Kirill Kolchin ***@***.***> wrote:  
 
 


@BAREBONESLDN what version of s_c are you using?
The archive above already has the hex file you need.
