### ISSUE TITLE
Missing scale and offset on the LFO

### ISSUE THREAD

**Issue by eh2k** [eh2k/squares-and-circles#89]
> I'm missing scale and offset on the LFO's. Maybe I just can't figure it out ?
> Also - Can you make a LFO like on a moog one (see the pic) ? 
I can't figure out the algorithm - but I use my own wavetable in VCV: https://github.com/jpnielsen/wavetables 

![image](https://github.com/eh2k/squares-and-circles/assets/27916597/e1ae6a32-9ecf-4c78-b7ae-db93d14ebb70)

_Originally posted by @jpnielsen in https://github.com/eh2k/squares-and-circles/issues/1#issuecomment-2135227560_

**Comment by mrmattallison** [comment]
Just wanted to add my voice to the mix. Scale and Offset would be great, both in the Modulation parameter option as we as the CV/LFO machiene. I'd love to see a SMOOTH Random option as well ala MI Peaks.

**Comment by eh2k** [comment]
@jpnielsen @mrmattallison 

CV/LFO Enhancements in the latest version

![image](https://github.com/user-attachments/assets/3ca909e9-7265-4147-ac95-3f8784c9a020)
