### ISSUE TITLE
custom fx do not load in the e030c30

### ISSUE THREAD

**Issue by koswir** [eh2k/squares-and-circles#93]
@eh2k 
Hey 😄 
Vacation ended and I am back at my modular.
Updated one of my o_c's to the latest and I can only run the build in fx 😞 (custom ones do not load at all).
I downgraded to fc2389f and fx work again but this version is pre save slots and copy features.
Could you please share the 9b81a8a which is the one I have on other o_cs and it works great?
I hope you had some great summer!
Cheers!

**Comment by eh2k** [comment]
Hi @koswir 

I actually had a longer summer break. 

I installed various CRC checks with my last update - unfortunately this also prevented old effects from being loaded (I assume you got a CRC error message).

In any case, I have updated the FX website, so newly flashed effects should now work again with the latest firmware.
